// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eytqmdssekkdlnoqzrzb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV5dHFtZHNzZWtrZGxub3F6cnpiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwNzUzMjIsImV4cCI6MjA2NzY1MTMyMn0.IUsVVZZ-GiX33zk1go8JAQjThdm9M4pv4dnEOv2dkJ0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});