// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jpbqehtcthvhhkpbcqxo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpwYnFlaHRjdGh2aGhrcGJjcXhvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5MTMxNjUsImV4cCI6MjA2NzQ4OTE2NX0.U7YLV5j92gmLvIN7HHXYpmiHPX1ayqzTi-Q67e35zSQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});